# Generated by Django 5.1.6 on 2025-07-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_submission'),
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
    ]
