# Generated by Django 5.1.6 on 2025-07-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
    ]
