# Generated by Django 5.2.4 on 2025-07-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tag_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
