# Generated by Django 5.1.6 on 2025-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_grade',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
